version: "3.7"
services:
  rest-api:
    environment:
      LOG_LEVEL: "30"
      HB_EXP: "30"
      REDIS_HOST: redis
      # SESSION_SECRET:
    build: ./
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - net_a
  redis:
    image: redis
    networks:
      - net_a
    ports:
      - "6379:6379"
networks:
  net_a: