version: "3.7"
services:
  rest-api:
    volumes:
      - ./app:/app/
    command:  python /app/main.py
    environment:
      LOG_LEVEL: warning
      HB_EXP: 30
      REDIS_HOST: redis
      PYTHONUNBUFFERED: 1
      # SESSION_SECRET:
    build: ./
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - net_a
  redis:
    image: redis
    networks:
      - net_a
    ports:
      - "6379:6379"
networks:
  net_a:



