version: 2
jobs:
  

  test:
    docker:
      - image: circleci/python:3.7
        environment:
          FLASK_CONFIG: testing
          REDIS_HOST: localhost
      - image: circleci/redis:5.0.7
      # - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: | 
            sudo python -m pip install -r /app/requirements.txt
      - run:
          name: Run Config Script
          command: |
            # sudo chmod +x load_secrets.sh
            bash ./load_secrets.sh
            cat ./client_secrets.json
      - run: 
          name: Test pylint and pycodestyle
          command: |
            pydocstyle /home/circleci/project/app/main.py
            pylint --disable=C,W,R /home/circleci/project/app/main.py
      - run:
          name: Test API routes
          command: |
            python -m pytest
  build:       
      - setup_remote_docker
      - run:
          name: Push Docker Repo
          command: |
            docker build -t $DOCKER_USER/led_iot_api:$CIRCLE_SHA1 .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/led_iot_api:$CIRCLE_SHA1

  deploy:
      - run:
          name: Push AWS
          command: aws s3 sync ./site s3://lights.ashleynewton.net
      - run:
          name: Deploy Fargate
          

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

