version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          FLASK_CONFIG: testing
          REDIS_HOST: localhost
      - image: circleci/redis:5.0.7
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: | 
            sudo python -m pip install -r requirements.txt
      - run: 
          name: Test pylint and pycodestyle
          command: |
            pydocstyle /home/circleci/project/app/main.py
            pylint --disable=C,W,R /home/circleci/project/app/main.py
      - run:
          name: Test API routes
          command: |
            python -m pytest
      
      # Install via apk on alpine based images
      # - run:
      #     name: Install Docker client
      #     command: apk add docker-cli

      - setup_remote_docker
      
      - run:
          name: Push Docker Repo
          command: |
            docker build -t $DOCKER_USER/led_iot_api:$CIRCLE_SHA1 .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/led_iot_api:$CIRCLE_SHA1