version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: pip3 install pydocstyle
      - run: pydocstyle /app/main.py
#    one:
#      docker:
#        - image: circleci/ruby:2.4.1
#      steps:
#        - checkout
#        - run: echo "A first hello"
#        - run: sleep 25
#    two:
#      docker:
#        - image: circleci/ruby:2.4.1
#      steps:
#        - checkout
#        - run: echo "A more familiar hi"
#        - run: sleep 15
#  workflows:
#    version: 2
#    one_and_two:
#      jobs:
#        - one
#        - two