version: 2
jobs:
  # shellcheck:
  #   docker:
  #     - image: koalaman/shellcheck-alpine:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: Check Scripts
  #         command: |
  #           find . -type f -name '*.sh' | wc -l
  #           find . -type f -name '*.sh' | xargs shellcheck --external-sources
  #           echo ls

  build-job:
    docker:
      - image: circleci/python:3.7
        environment:
          FLASK_CONFIG: testing
          REDIS_HOST: localhost
      - image: circleci/redis:5.0.7
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: | 
            sudo python -m pip install -r requirements.txt
      - run:
        name: Check Scripts
        command: |
          find . -type f -name '*.sh' | wc -l
          find . -type f -name '*.sh' | xargs shellcheck --external-sources
          echo ls
      - run: 
          name: Test pylint and pycodestyle
          command: |
            pydocstyle /home/circleci/project/app/main.py
            pylint --disable=C,W,R /home/circleci/project/app/main.py
      - run:
          name: Test API routes
          command: |
            python -m pytest
      
      # Install via apk on alpine based images
      # - run:
      #     name: Install Docker client
      #     command: apk add docker-cli

      - setup_remote_docker
      
      - run:
          name: Push Docker Repo
          command: |
            docker build -t $DOCKER_USER/led_iot_api:$CIRCLE_SHA1 .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/led_iot_api:$CIRCLE_SHA1

# workflows:
#   version: 2
#   workflow:
#     jobs:
#       - shellcheck
#       - build-job:
#           requires:
#             - shellcheck